services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=demo_workshop
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
    ports:
      - '3306:3306'
